/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.material;

import view.admin.*;
import controler.campos.ManipularCampos;
import controler.telas.ManipulaTelas;
import java.awt.Color;
import java.awt.Toolkit;
import static java.lang.Math.random;
import java.util.Calendar;
import java.util.Date;
import javax.swing.border.LineBorder;
import model.Pessoa;
import java.util.Random;

/**
 *
 * @author maikon.rosa
 */
public class NovoMaterial extends javax.swing.JFrame {

    ManipulaTelas telas = new ManipulaTelas();
    ManipularCampos campos = new ManipularCampos();
    Pessoa pessoa = new Pessoa();

    /**
     * Creates new form T_tela_inicial
     */
    public NovoMaterial() {
        initComponents();
        setLocationRelativeTo(null);
        this.setIconImage(Toolkit.getDefaultToolkit().getImage("src/recursos/imagens/Logo.png"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField7 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        fechar = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fornecedor = new javax.swing.JTextField();
        erro_fornecedor = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        erro_email = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        erro_f_compra = new javax.swing.JLabel();
        f_compra = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        check_telefone = new javax.swing.JCheckBox();
        chek_email = new javax.swing.JCheckBox();
        jLabel21 = new javax.swing.JLabel();
        telefone = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        link_compra = new javax.swing.JTextField();
        erro_tel = new javax.swing.JLabel();
        erro_link = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        material = new javax.swing.JTextField();
        erro_material = new javax.swing.JLabel();
        valor_unit = new javax.swing.JTextField();
        erro_v_unit = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        uni_medida = new javax.swing.JComboBox<>();
        erro_medida = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        qtd_compra = new javax.swing.JTextField();
        erro_qtd = new javax.swing.JLabel();
        chek_desconto = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        valor_desc = new javax.swing.JTextField();
        erro_desconto = new javax.swing.JLabel();
        tipo_desconto = new javax.swing.JComboBox<>();
        btn_cad = new javax.swing.JButton();

        jTextField7.setText("jTextField7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Minha produção");
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setType(java.awt.Window.Type.POPUP);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 204), new java.awt.Color(0, 102, 255), new java.awt.Color(0, 51, 204), new java.awt.Color(0, 153, 153)));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 204));
        jLabel2.setText("Novo Material  ");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagens/logo_size.jpg"))); // NOI18N

        jLabel10.setText("By. Maikon C.P. Rosa ");

        jLabel11.setText("Sistema V. 1");

        fechar.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        fechar.setForeground(new java.awt.Color(255, 0, 0));
        fechar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fechar.setText("X");
        fechar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 1, true));
        fechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fecharMouseClicked(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204)), "Dados de compra", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tw Cen MT", 0, 18), new java.awt.Color(0, 102, 204))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Fornecedor :");

        fornecedor.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        fornecedor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        fornecedor.setBorder(new LineBorder(new Color(0, 102, 153)));

        erro_fornecedor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        erro_fornecedor.setForeground(new java.awt.Color(255, 0, 0));
        erro_fornecedor.setText("X");

        email.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        email.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        erro_email.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        erro_email.setForeground(new java.awt.Color(255, 0, 0));
        erro_email.setText("X");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("E-mail :");

        erro_f_compra.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        erro_f_compra.setForeground(new java.awt.Color(255, 0, 0));
        erro_f_compra.setText("X");

        f_compra.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        f_compra.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Loja virtual (Internet)", "Loja fisica " }));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("Forma de compra :");

        check_telefone.setBackground(new java.awt.Color(255, 255, 255));
        check_telefone.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        check_telefone.setText("Telefone ");

        chek_email.setBackground(new java.awt.Color(255, 255, 255));
        chek_email.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        chek_email.setText("E-mail");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText("Telefone :");

        telefone.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        telefone.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("Link da compra: ");

        link_compra.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        link_compra.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        erro_tel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        erro_tel.setForeground(new java.awt.Color(255, 0, 0));
        erro_tel.setText("X");

        erro_link.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        erro_link.setForeground(new java.awt.Color(255, 0, 0));
        erro_link.setText("X");

        jSeparator1.setBackground(new java.awt.Color(0, 102, 204));
        jSeparator1.setForeground(new java.awt.Color(0, 51, 255));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Nome do material :");

        material.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        material.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        fornecedor.setBorder(new LineBorder(new Color(0, 102, 153)));

        erro_material.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        erro_material.setForeground(new java.awt.Color(255, 0, 0));
        erro_material.setText("X");

        valor_unit.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        valor_unit.setText("R$ 0,00");
        valor_unit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        fornecedor.setBorder(new LineBorder(new Color(0, 102, 153)));
        valor_unit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valor_unitActionPerformed(evt);
            }
        });

        erro_v_unit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        erro_v_unit.setForeground(new java.awt.Color(255, 0, 0));
        erro_v_unit.setText("X");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Valor Unitario :");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setText("Unidade de medida :");

        uni_medida.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        uni_medida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "km", "m", "cm", "l", "ml", "kg", "g", "mg" }));

        erro_medida.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        erro_medida.setForeground(new java.awt.Color(255, 0, 0));
        erro_medida.setText("X");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Quatidade comprada:");

        qtd_compra.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        qtd_compra.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        fornecedor.setBorder(new LineBorder(new Color(0, 102, 153)));

        erro_qtd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        erro_qtd.setForeground(new java.awt.Color(255, 0, 0));
        erro_qtd.setText("X");

        chek_desconto.setBackground(new java.awt.Color(255, 255, 255));
        chek_desconto.setText("Desconto ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Valor de desconto :");

        valor_desc.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        valor_desc.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        fornecedor.setBorder(new LineBorder(new Color(0, 102, 153)));
        valor_desc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valor_descActionPerformed(evt);
            }
        });

        erro_desconto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        erro_desconto.setForeground(new java.awt.Color(255, 0, 0));
        erro_desconto.setText("X");

        tipo_desconto.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        tipo_desconto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "R$", "%", " " }));

        btn_cad.setBackground(new java.awt.Color(0, 102, 153));
        btn_cad.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        btn_cad.setText("Cadastrar ");
        btn_cad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cadMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel22)
                    .addComponent(chek_email)
                    .addComponent(jLabel21)
                    .addComponent(jLabel7)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(link_compra, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(erro_link))
                    .addComponent(check_telefone)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(email, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                            .addComponent(telefone))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(erro_tel)
                            .addComponent(erro_email)))
                    .addComponent(jLabel20)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(f_compra, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(erro_f_compra))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(erro_fornecedor)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(material, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(erro_material))
                            .addComponent(jLabel4)
                            .addComponent(jLabel23)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(uni_medida, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(erro_medida))
                            .addComponent(jLabel5)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(qtd_compra, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(erro_qtd))
                            .addComponent(chek_desconto)
                            .addComponent(jLabel6)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(valor_desc)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tipo_desconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(valor_unit, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(erro_v_unit)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(erro_desconto)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 248, Short.MAX_VALUE)
                        .addComponent(btn_cad, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(12, 12, 12)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(erro_fornecedor))
                                .addGap(21, 21, 21)
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(f_compra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(erro_f_compra))
                                .addGap(27, 27, 27)
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(link_compra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(erro_link))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(check_telefone)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(erro_tel))
                                .addGap(18, 18, 18)
                                .addComponent(chek_email)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(erro_email)))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(material, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(erro_material))
                        .addGap(24, 24, 24)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(uni_medida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(erro_medida))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(qtd_compra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(erro_qtd))
                        .addGap(26, 26, 26)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(erro_v_unit)
                            .addComponent(valor_unit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(chek_desconto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(valor_desc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tipo_desconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(erro_desconto))
                        .addGap(60, 60, 60)
                        .addComponent(btn_cad, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(479, 479, 479)
                        .addComponent(jLabel10)
                        .addGap(183, 183, 183)
                        .addComponent(jLabel11)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(fechar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fechar)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fecharMouseClicked
        dispose();
    }//GEN-LAST:event_fecharMouseClicked

    private void btn_cadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cadMouseClicked
        boolean cad = true;
      //Fornecedor
        if (pessoa.setP_nome(fornecedor.getText()) == false) {
            campos.JtextFieldErro(fornecedor,erro_fornecedor, false);
            cad = false;
        } else {
            campos.JtextFieldErro(fornecedor,erro_fornecedor, true);
        }
    // Forma de compra 
        if (pessoa.setP_cpf(txt_cpf.getText()) == false) {
            campos.JtextFieldErro(txt_cpf,erro_cpf, false);
            cad = false;
        } else {
            campos.JtextFieldErro(txt_cpf,erro_cpf, true);
        }
    //E-mail
        if (pessoa.setP_email(email.getText()) == false) {
            campos.JtextFieldErro(email,erro_email, false);
            cad = false;
        } else {
            campos.JtextFieldErro(email,erro_email, true);
        }
    //Usuario 
        if (pessoa.setU_nome(txt_usuario.getText()) == false) {
            campos.JtextFieldErro(txt_usuario,erro_usu, false);
            cad = false;
        } else {
            campos.JtextFieldErro(txt_usuario,erro_usu, true);
        }
    //Senha    
        if (pessoa.setU_senhaAdmin(txt_senha.getText()) == false) {
            campos.JpassFielErro(txt_senha,erro_senha, false);
            cad = false;
        } else {
            campos.JpassFielErro(txt_senha,erro_senha,true);
        }
       
    //Função 
    if (pessoa.setU_funcao(s_funcao.getSelectedIndex()) == false) {
            campos.JComboBoxErro(s_funcao, erro_func,false);
            cad = false;
        } else {
            campos.JComboBoxErro(s_funcao,erro_func,true);
        }
        System.out.print(cad);
        if (cad == true) {
            System.out.println("Nome :" + pessoa.getP_nome());
            System.out.println("Cpf :" + pessoa.getP_email());
            System.out.println("E-mail :" + pessoa.getP_cpf());
            System.out.println("Usuario :" + pessoa.getU_nome());
            System.out.println("Senha :" + pessoa.getU_senha());
        
        }
    }//GEN-LAST:event_btn_cadMouseClicked

    private void valor_unitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valor_unitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valor_unitActionPerformed

    private void valor_descActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valor_descActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valor_descActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NovoMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NovoMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NovoMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NovoMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NovoMaterial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cad;
    private javax.swing.JCheckBox check_telefone;
    private javax.swing.JCheckBox chek_desconto;
    private javax.swing.JCheckBox chek_email;
    private javax.swing.JTextField email;
    private javax.swing.JLabel erro_desconto;
    private javax.swing.JLabel erro_email;
    private javax.swing.JLabel erro_f_compra;
    private javax.swing.JLabel erro_fornecedor;
    private javax.swing.JLabel erro_link;
    private javax.swing.JLabel erro_material;
    private javax.swing.JLabel erro_medida;
    private javax.swing.JLabel erro_qtd;
    private javax.swing.JLabel erro_tel;
    private javax.swing.JLabel erro_v_unit;
    private javax.swing.JComboBox<String> f_compra;
    private javax.swing.JLabel fechar;
    private javax.swing.JTextField fornecedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField link_compra;
    private javax.swing.JTextField material;
    private javax.swing.JTextField qtd_compra;
    private javax.swing.JTextField telefone;
    private javax.swing.JComboBox<String> tipo_desconto;
    private javax.swing.JComboBox<String> uni_medida;
    private javax.swing.JTextField valor_desc;
    private javax.swing.JTextField valor_unit;
    // End of variables declaration//GEN-END:variables
}
